# run this playbook in test mode:
#  ansible-playbook --inventory localhost, --check --diff cvmfs.yaml
# creates ~/.ansible directory for temporary storage

- name: install CVMFS
  hosts: localhost
  connection: local	# do not use ssh
  gather_facts: no	# save time

  vars:			# local to this playbook

    cvmfs_packages:
      - cvmfs
      - cvmfs-server
      - httpd
      - osg-oasis
      - osg-release	# install to make cvmfs visible to yum

  tasks:

    - name: create cvmfs_colorado group
      group:
        name: cvmfs_colorado
        state: present

    - name: create cvmfs_colorado account
      user:
        name: cvmfs_colorado
        group: cvmfs_colorado
        shell: /bin/bash
        state: present

    - name: install trusted OSG repo GPG key
      copy:
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-OSG
        content: |
          -----BEGIN PGP PUBLIC KEY BLOCK-----
          Version: GnuPG v1.4.5 (GNU/Linux)

          mQGiBE5ybYARBACoIzzlLbh1sHK+9CCU32JrOf0Q3LYcneFxhmoQMo7nZOKZB8eT
          8a869LFVHxD/ONGoEgF7kIuUKYKOWmDgTzYXZVDZqyjDXVs5McldeAbwHHkPEFA1
          nCfGVcHT/EILhxxUXgRXIuRs+yvsCDiS3iuq4vIj18vCswD9azbRM1whawCg/5Tv
          pMm7Ng8pgYLMT8TEJhWTICsD/1GMamQvuO/VmW7lO83BtjbMYpu/UL/EfVbCYQmA
          yZ+GetKOq+BWnVLtHVP1/gvz/iIhf4nps5k+4GVrb8A0b5yaqBRO5lxhiqglYSRf
          5qgDOgWwR8PdDO55yyrt0kyvmBM8MNaOhFLHc5ZJZKRVy4Tm2lmeBmP417XqrtXT
          KbbTA/0ULRy6/LXCgwmOKHgzhbTmbXfTTkEtfwRqmwLlLrr92otuizADfZ7dXHZK
          3Wk8/L2gJIvgQ0+5LGzDwI5T7ZKrCKpeGE0SbxVrxiY3WAm7ma0nwUEDvJNfuFYi
          r+4N4OjRjbjb33kpooNUipBYKToioSvNyKt87Dq0k3cA4BX5f7RXT1NHIFNvZnR3
          YXJlIFRlYW0gKFJQTSBTaWduaW5nIEtleSBmb3IgS29qaSBQYWNrYWdlcykgPHZk
          dC1zdXBwb3J0QG9wZW5zY2llbmNlZ3JpZC5vcmc+iGAEExECACAFAk5ybYACGwMG
          CwkIBwMCBBUCCAMEFgIDAQIeAQIXgAAKCRAhELHIgkuGA67QAKCZXGGlOhdyde6a
          f3lNRdwF4TmEeQCg8iMaMsRQ4ExtMzfp04mpFoH4wSC5Ag0ETnJtgxAIALNB1L3t
          sQ+jNB3OrHFXsSfg2Nlk88f+xmZ+Sbe0+e5E5SCM2bnE6uUNvaHNw2+yajO5/UxX
          mavpe5uz+LtMn8ep+VKG2twdRDJ/WU76vINcORAPS5ezIcBxtuA9sXRS5hOgxnzU
          Z6B7rO1w3OuPJ7egLXX0t+ZYvNeKiccXn2njwFtDWzlrfjl600/xWrG3MHwHtRU/
          SjU6AmaqYSpw4Xb0ZW7yL8nni8AZLXmVsEvbX7vOVK/SGPCo62m4s2uEaL/RPIbu
          vj2M7sbRHDh0twpGG5MY6XslZXMghT79Q9YqqBOtyF74JRxtegnI87i/YT4LVJwm
          6AfZHpuYArkp5T8ABAsH/1PxpdyZc+tdzmwRTwOYrTfvsOyhgXgmtkWhJcfw2A3P
          GPTP2mVBhNJGK7SoYYVHf0Zhc/tmNG+3GRc4JIL8DF+AyO6/+fyD4XIni8OiWOiX
          gsBLqy3L3TrTTcffYcPwN6ZMnjkW8l4Hf+xyr39eAlXq6Uzd0ICTglqA3cZaZvcX
          gLx8xn69Md88SqaUFb3Os+i6ZAd/w9WqfmxbwVhVuhodKKMB2YIL6kk6DbA/SIzP
          kcen36OtFsGqgWptaJcWIXqKId8a9EtWvOIFu9HaMvdh9jA9OTLLk3ZCBNMdAdfy
          flf96qm/IhBuG0IWw7i3jLKxYiSifhpdUIjeI47XynyISQQYEQIACQUCTnJtgwIb
          DAAKCRAhELHIgkuGA5CbAJ0XXzu4BqSd501YGAVXA6hg+vTCngCeN8YQA1CtXRMg
          t33FOtH+gLL8Quw=
          =f6aQ
          -----END PGP PUBLIC KEY BLOCK-----
        backup: yes
        owner: '0'
        group: '0'
        mode: 0644

    # use this to make check mode work better
    - name: is OSG repo GPG key file present?
      stat:
        path: /etc/pki/rpm-gpg/RPM-GPG-KEY-OSG
      register: osg_repo_key_file

    - name: is OSG repo GPG key already imported?
      command: rpm -q --quiet gpg-pubkey-824b8603-4e726d80
      args:
        warn: no		# ok to use rpm instead of yum in module
      check_mode: no		# pretend we are not in check mode so command is always run
      changed_when: false	# no side effects
      failed_when: false	# ok for key to be not imported
      register: have_osg_repo_key

    - name: import OSG repo GPG key into rpm database
      command: rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-OSG
      args:
        warn: no		# ok to use rpm instead of yum in module
      check_mode: no		# pretend we are not in check mode so command is always run
      changed_when: have_osg_repo_key.rc != 0
      when:
        - have_osg_repo_key.rc != 0
        - osg_repo_key_file.stat.exists

    - name: install osg-release package
      package:
        name: https://repo.opensciencegrid.org/osg/3.6/osg-3.6-el7-release-latest.rpm
        state: present

    # use this to make check mode work better
    - name: is OSG release package installed?
      command: rpm -q --quiet osg-release
      args:
        warn: no		# ok to use rpm instead of yum in module
      check_mode: no		# pretend we are not in check mode so command is always run
      changed_when: false	# no side effects
      failed_when: false	# ok for package to be not installed
      register: osg_release_installed

    - name: install CVMFS packages
      yum:
        name: "{{ cvmfs_packages }}"
        state: present
      when: osg_release_installed.rc == 0

    # use this to make check mode work better
    - name: is Apache web server package installed?
      command: rpm -q --quiet httpd
      args:
        warn: no		# ok to use rpm instead of yum in module
      check_mode: no		# pretend we are not in check mode so command is always run
      changed_when: false	# no side effects
      failed_when: false	# ok for package to be not installed
      register: httpd_package_installed

    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: yes
      when: httpd_package_installed.rc == 0

    - name: establish CVMFS re-sign cron job
      cron:
        name: re-sign cvmfs whitelist
        user: root
        day: "1"
        hour: "16"	# UTC, mid-morning in the United States
        minute: "3"
        job: cvmfs_server resign -f -d 35 colorado.xsede.org > /dev/null
      when: "'/srv/cvmfs/colorado.xsede.org/.cvmfswhitelist' is file"

#    - name: print all Ansible variables
#      debug:
#        var: vars
